spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mySite
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    session:
      timeout: 1800

logging:
  level:
    org.hibernate.sql: debug

